import { z } from "zod";
import { FormFieldConfig } from "@/components/admin/DynamicForm";

export interface AdminTabConfig {
  title: string;
  description: string;
  apiEndpoint: string;
  fields: FormFieldConfig[];
  displayColumns: Array<{
    key: string;
    label: string;
    sortable?: boolean;
    filterable?: boolean;
    render?: string;
    width?: string;
  }>;
  searchFields: string[];
  defaultSort: { field: string; order: "asc" | "desc" };
}

export const adminConfigs: Record<string, AdminTabConfig> = {
  users: {
    title: "User Management",
    description: "Manage admin users and their permissions",
    apiEndpoint: "/api/admin/users",
    fields: [
      {
        name: "username",
        label: "Username",
        type: "text",
        required: true,
        placeholder: "Enter username",
        validation: z.string().min(3, "Username must be at least 3 characters"),
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        placeholder: "Enter email address",
        validation: z.string().email("Please enter a valid email address"),
      },
      {
        name: "password",
        label: "Password",
        type: "password",
        required: true,
        placeholder: "Enter secure password",
        validation: z.string().min(8, "Password must be at least 8 characters"),
      },
      {
        name: "role",
        label: "Role",
        type: "select",
        required: true,
        options: [
          { value: "admin", label: "🔑 Administrator" },
          { value: "moderator", label: "⚖️ Moderator" },
          { value: "editor", label: "✏️ Editor" },
        ],
        validation: z.enum(["admin", "moderator", "editor"]),
      },
      {
        name: "isActive",
        label: "Account Status",
        type: "select",
        required: true,
        options: [
          { value: "true", label: "✅ Active" },
          { value: "false", label: "❌ Inactive" },
        ],
        validation: z.boolean(),
      },
    ],
    displayColumns: [
      { key: "username", label: "Username", sortable: true, width: "20%" },
      { key: "email", label: "Email", sortable: true, width: "25%" },
      { key: "role", label: "Role", sortable: true, render: "badge", width: "15%" },
      { key: "isActive", label: "Status", render: "boolean", width: "10%" },
      { key: "lastLogin", label: "Last Login", sortable: true, render: "date", width: "15%" },
      { key: "createdAt", label: "Created", sortable: true, render: "date", width: "15%" },
    ],
    searchFields: ["username", "email", "role"],
    defaultSort: { field: "createdAt", order: "desc" },
  },

  contact: {
    title: "Contact Messages",
    description: "View and manage contact form submissions with advanced status tracking",
    apiEndpoint: "/api/admin/contact",
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        placeholder: "Contact name",
        validation: z.string().min(2, "Name must be at least 2 characters"),
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        placeholder: "Contact email",
        validation: z.string().email("Please enter a valid email address"),
      },
      {
        name: "subject",
        label: "Subject",
        type: "text",
        required: true,
        placeholder: "Message subject",
        validation: z.string().min(5, "Subject must be at least 5 characters"),
      },
      {
        name: "message",
        label: "Message",
        type: "textarea",
        required: true,
        placeholder: "Message content",
        validation: z.string().min(10, "Message must be at least 10 characters"),
      },
      {
        name: "phoneNumber",
        label: "Phone Number",
        type: "text",
        placeholder: "Optional phone number",
      },
      {
        name: "company",
        label: "Company",
        type: "text",
        placeholder: "Optional company name",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { value: "unread", label: "🔵 Unread" },
          { value: "read", label: "👁️ Read" },
          { value: "replied", label: "✅ Replied" },
          { value: "archived", label: "📁 Archived" },
        ],
        validation: z.enum(["unread", "read", "replied", "archived"]),
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "low", label: "🟢 Low" },
          { value: "medium", label: "🟡 Medium" },
          { value: "high", label: "🟠 High" },
          { value: "urgent", label: "🔴 Urgent" },
        ],
        validation: z.enum(["low", "medium", "high", "urgent"]),
      },
      {
        name: "adminNotes",
        label: "Admin Notes",
        type: "textarea",
        placeholder: "Internal notes for this message...",
      },
      {
        name: "tags",
        label: "Tags",
        type: "text",
        placeholder: "Comma-separated tags (e.g., follow-up, client, urgent)",
      },
    ],
    displayColumns: [
      { key: "name", label: "Name", sortable: true, width: "15%" },
      { key: "email", label: "Email", sortable: true, width: "20%" },
      { key: "subject", label: "Subject", sortable: true, width: "25%" },
      { key: "status", label: "Status", sortable: true, render: "status", width: "10%" },
      { key: "priority", label: "Priority", sortable: true, render: "priority", width: "10%" },
      { key: "isRead", label: "Read", render: "boolean", width: "8%" },
      { key: "createdAt", label: "Date", sortable: true, render: "date", width: "12%" },
    ],
    searchFields: ["name", "email", "subject", "company", "tags"],
    defaultSort: { field: "createdAt", order: "desc" },
  },

  messages: {
    title: "Contact Messages",
    description: "Manage contact form submissions and inquiries",
    apiEndpoint: "/api/admin/messages",
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        placeholder: "John Doe",
        validation: z.string().min(1, "Name is required"),
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        placeholder: "john@example.com",
        validation: z.string().email("Please enter a valid email address"),
      },
      {
        name: "subject",
        label: "Subject",
        type: "text",
        required: true,
        placeholder: "Project Inquiry",
        validation: z.string().min(1, "Subject is required"),
      },
      {
        name: "message",
        label: "Message",
        type: "textarea",
        required: true,
        placeholder: "Your message here...",
        validation: z.string().min(10, "Message must be at least 10 characters"),
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { value: "unread", label: "🔵 Unread" },
          { value: "read", label: "👁️ Read" },
          { value: "replied", label: "✅ Replied" },
          { value: "archived", label: "📁 Archived" },
        ],
        validation: z.enum(["unread", "read", "replied", "archived"]),
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "low", label: "🟢 Low" },
          { value: "medium", label: "🟡 Medium" },
          { value: "high", label: "🟠 High" },
          { value: "urgent", label: "🔴 Urgent" },
        ],
        validation: z.enum(["low", "medium", "high", "urgent"]),
      },
    ],
    displayColumns: [
      { key: "name", label: "Name", sortable: true, width: "15%" },
      { key: "email", label: "Email", sortable: true, width: "20%" },
      { key: "subject", label: "Subject", sortable: true, width: "25%" },
      { key: "status", label: "Status", sortable: true, render: "status", width: "12%" },
      { key: "priority", label: "Priority", sortable: true, render: "priority", width: "12%" },
      { key: "createdAt", label: "Received", sortable: true, render: "date", width: "16%" },
    ],
    searchFields: ["name", "email", "subject", "message"],
    defaultSort: { field: "createdAt", order: "desc" },
  },

  "hero-content": {
    title: "Hero Section",
    description: "Manage homepage hero section content",
    apiEndpoint: "/api/admin/hero-content",
    fields: [
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        required: true,
        placeholder: "Your last name",
      },
      {
        name: "title",
        label: "Professional Title",
        type: "text",
        required: true,
        placeholder: "e.g., Software Developer",
      },
      {
        name: "tagline",
        label: "Tagline",
        type: "textarea",
        required: true,
        placeholder: "Brief description or tagline",
      },
      {
        name: "roles",
        label: "Roles (one per line)",
        type: "textarea",
        required: true,
        placeholder: "Computer Science & Engineering Student\nCloud Engineer\nDevOps Engineer\nSoftware Developer",
      },
      {
        name: "heroImage",
        label: "Hero Image URL",
        type: "text",
        placeholder: "/path/to/image.jpg",
      },
      {
        name: "resumeUrl",
        label: "Resume URL",
        type: "text",
        placeholder: "/path/to/resume.pdf",
      },
      {
        name: "resumeLabel",
        label: "Resume Button Label",
        type: "text",
        placeholder: "Download Resume",
      },
    ],
    displayColumns: [
      { key: "firstName", label: "First Name", sortable: true },
      { key: "lastName", label: "Last Name", sortable: true },
      { key: "title", label: "Title", sortable: true },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date" },
    ],
    searchFields: ["firstName", "lastName", "title"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  about: {
    title: "About Section Cards",
    description: "Manage individual about section cards: Biography, Problem Solver, Continuous Learner, DevOps Specialist, and Aspirations",
    apiEndpoint: "/api/admin/about",
    fields: [
      {
        name: "sectionType",
        label: "Section Type",
        type: "select",
        required: true,
        options: [
          { value: "main", label: "🏠 Main About Header" },
          { value: "biography", label: "📖 Biography Card" },
          { value: "problem-solver", label: "🔧 Problem Solver Card" },
          { value: "continuous-learner", label: "📚 Continuous Learner Card" },
          { value: "devops-specialist", label: "⚙️ DevOps Specialist Card" },
          { value: "aspirations", label: "🚀 Aspirations Card" },
        ],
        validation: z.enum(["main", "biography", "problem-solver", "continuous-learner", "devops-specialist", "aspirations"]),
      },
      {
        name: "title",
        label: "Card Title",
        type: "text",
        required: true,
        placeholder: "Biography, Problem Solver, etc.",
        validation: z.string(),
      },
      {
        name: "subtitle",
        label: "Card Subtitle",
        type: "text",
        placeholder: "Optional subtitle for the card",
      },
      {
        name: "content",
        label: "Card Content",
        type: "textarea",
        required: true,
        placeholder: "Main content text for this card section...",
        validation: z.string(),
      },
      {
        name: "icon",
        label: "Card Icon",
        type: "text",
        placeholder: "📖, 🔧, 📚, ⚙️, 🚀, etc.",
        description: "Emoji or icon for this card",
      },
      {
        name: "imageUrl",
        label: "Card Image URL",
        type: "text",
        placeholder: "/images/about-card.jpg",
        description: "Optional image for this card",
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        required: true,
        placeholder: "1",
        validation: z.number().min(0),
      },
      {
        name: "isActive",
        label: "Active Status",
        type: "select",
        required: true,
        options: [
          { value: "true", label: "✅ Active" },
          { value: "false", label: "❌ Inactive" },
        ],
        validation: z.boolean(),
      },
    ],
    displayColumns: [
      { key: "sectionType", label: "Type", sortable: true, render: "badge", width: "20%" },
      { key: "title", label: "Title", sortable: true, width: "25%" },
      { key: "icon", label: "Icon", sortable: false, width: "8%" },
      { key: "isActive", label: "Status", render: "boolean", width: "10%" },
      { key: "displayOrder", label: "Order", sortable: true, width: "10%" },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date", width: "20%" },
    ],
    searchFields: ["title", "content", "sectionType"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },





  education: {
    title: "Education Timeline",
    description: "Manage educational background with timeline display",
    apiEndpoint: "/api/admin/education",
    fields: [
      {
        name: "degree",
        label: "Degree/Course Title",
        type: "text",
        required: true,
        placeholder: "B.Tech in Computer Science and Engineering",
        validation: z.string().min(2, "Degree must be at least 2 characters"),
      },
      {
        name: "institution",
        label: "Institution/School Name",
        type: "text",
        required: true,
        placeholder: "Asansol Engineering College, Asansol",
        validation: z.string().min(2, "Institution must be at least 2 characters"),
      },
      {
        name: "educationType",
        label: "Education Level",
        type: "select",
        required: true,
        options: [
          { value: "university", label: "🎓 University/College" },
          { value: "higher-secondary", label: "📚 Higher Secondary" },
          { value: "secondary", label: "🏫 Secondary" },
          { value: "certification", label: "📜 Certification" },
          { value: "other", label: "📋 Other" },
        ],
        validation: z.enum(["university", "higher-secondary", "secondary", "certification", "other"]),
      },
      {
        name: "startDate",
        label: "Start Date",
        type: "text",
        required: true,
        placeholder: "August 2021",
        validation: z.string(),
      },
      {
        name: "endDate",
        label: "End Date",
        type: "text",
        placeholder: "June 2025 (or leave empty if ongoing)",
      },
      {
        name: "year",
        label: "Display Year Range",
        type: "text",
        required: true,
        placeholder: "August 2021 - June 2025",
        description: "How the year range appears on timeline",
        validation: z.string(),
      },
      {
        name: "result",
        label: "Result/Grade",
        type: "text",
        placeholder: "CGPA: 7.58/10 or Percentage: 73.83%",
        description: "CGPA, percentage, or grade achieved",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        placeholder: "Asansol, West Bengal",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Relevant coursework, achievements, activities, etc.",
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "1",
        description: "Order in timeline (lower numbers appear first)",
        validation: z.number().min(0),
      },
      {
        name: "isActive",
        label: "Show on Website",
        type: "switch",
        required: false,
        description: "Toggle to show or hide this education item on the website",
        validation: z.boolean().default(true),
      },
    ],
    displayColumns: [
      { key: "degree", label: "Degree", sortable: true, width: "30%" },
      { key: "institution", label: "Institution", sortable: true, width: "25%" },
      { key: "educationType", label: "Type", sortable: true, render: "badge", width: "12%" },
      { key: "year", label: "Year Range", sortable: true, width: "15%" },
      { key: "result", label: "Result", sortable: false, width: "10%" },
      { key: "isActive", label: "Status", render: "boolean", width: "8%" },
    ],
    searchFields: ["degree", "institution", "year", "result"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  "projects-content": {
    title: "Projects Section Content",
    description: "Manage the Projects section header, description, and GitHub button",
    apiEndpoint: "/api/admin/projects-content",
    fields: [
      {
        name: "sectionTag",
        label: "Section Tag",
        type: "text",
        required: true,
        placeholder: "My Work",
        validation: z.string().min(1, "Section tag is required"),
      },
      {
        name: "sectionTitle",
        label: "Section Title",
        type: "text",
        required: true,
        placeholder: "Featured Projects",
        validation: z.string().min(1, "Section title is required"),
      },
      {
        name: "sectionDescription",
        label: "Section Description",
        type: "textarea",
        required: true,
        placeholder: "Here are some of the key projects I've worked on, showcasing my technical skills and problem-solving abilities.",
        validation: z.string().min(1, "Section description is required"),
      },
      {
        name: "githubButtonText",
        label: "GitHub Button Text",
        type: "text",
        required: true,
        placeholder: "View All Projects on GitHub",
        validation: z.string().min(1, "GitHub button text is required"),
      },
      {
        name: "githubButtonUrl",
        label: "GitHub Button URL",
        type: "text",
        required: true,
        placeholder: "https://github.com/NoorainRaza23",
        validation: z.string().url("Must be a valid URL"),
      },
      {
        name: "isActive",
        label: "Active Status",
        type: "select",
        required: true,
        options: [
          { value: "true", label: "✅ Active" },
          { value: "false", label: "❌ Inactive" },
        ],
        validation: z.boolean(),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "0",
        validation: z.number().min(0),
      },
    ],
    displayColumns: [
      { key: "sectionTag", label: "Tag", sortable: true, width: "15%" },
      { key: "sectionTitle", label: "Title", sortable: true, width: "20%" },
      { key: "sectionDescription", label: "Description", sortable: false, width: "25%" },
      { key: "githubButtonText", label: "Button Text", sortable: false, width: "15%" },
      { key: "isActive", label: "Active", sortable: true, render: "boolean", width: "8%" },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date", width: "12%" },
      { key: "actions", label: "Actions", sortable: false, width: "5%" },
    ],
    searchFields: ["sectionTag", "sectionTitle", "sectionDescription", "githubButtonText"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  "education-content": {
    title: "Education Section Content",
    description: "Manage education section header, descriptions, and certification link",
    apiEndpoint: "/api/admin/education-content",
    fields: [
      {
        name: "sectionTitle",
        label: "Section Title",
        type: "text",
        required: true,
        placeholder: "Education",
        validation: z.string().min(1, "Section title is required"),
      },
      {
        name: "sectionSubtitle",
        label: "Section Subtitle",
        type: "text",
        required: true,
        placeholder: "Academic Background",
        validation: z.string().min(1, "Section subtitle is required"),
      },
      {
        name: "sectionDescription",
        label: "Section Description",
        type: "textarea",
        required: true,
        placeholder: "My academic journey and qualifications that have shaped my professional development.",
        validation: z.string().min(10, "Description must be at least 10 characters"),
      },
      {
        name: "bottomDescription",
        label: "Bottom Description",
        type: "textarea",
        required: true,
        placeholder: "My education has provided me with a strong foundation in computer science, engineering principles, and problem-solving methodologies that I apply to my work every day.",
        validation: z.string().min(10, "Bottom description must be at least 10 characters"),
      },
      {
        name: "certificationsLinkText",
        label: "Certifications Link Text",
        type: "text",
        required: true,
        placeholder: "View My Professional Certifications →",
        validation: z.string().min(1, "Link text is required"),
      },
      {
        name: "certificationsLinkUrl",
        label: "Certifications Link URL",
        type: "text",
        required: true,
        placeholder: "#certifications",
        validation: z.string().min(1, "Link URL is required"),
      },
    ],
    displayColumns: [
      { key: "sectionTitle", label: "Title", sortable: true, width: "20%" },
      { key: "sectionSubtitle", label: "Subtitle", sortable: true, width: "20%" },
      { key: "certificationsLinkText", label: "Link Text", sortable: false, width: "25%" },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date", width: "15%" },
    ],
    searchFields: ["sectionTitle", "sectionSubtitle"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  experience: {
    title: "Work Experience",
    description: "Manage professional work experience and career history",
    apiEndpoint: "/api/admin/experience",
    fields: [
      {
        name: "position",
        label: "Position",
        type: "text",
        required: true,
        placeholder: "Software Developer, DevOps Intern",
        validation: z.string().min(2, "Position is required"),
      },
      {
        name: "company",
        label: "Company",
        type: "text",
        required: true,
        placeholder: "Edunet Foundation, Calsoft",
        validation: z.string().min(2, "Company name is required"),
      },
      {
        name: "duration",
        label: "Duration",
        type: "text",
        required: true,
        placeholder: "Dec 2023 - Jan 2024, 2023",
        description: "How the duration appears on the timeline",
        validation: z.string().min(4, "Duration is required"),
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        placeholder: "Remote, Kolkata",
        description: "Work location (optional)",
      },
      {
        name: "description",
        label: "Job Description",
        type: "textarea",
        placeholder: "Brief overview of the role and key achievements...",
        description: "Optional summary description of the role",
      },
      {
        name: "responsibilities",
        label: "Key Responsibilities",
        type: "textarea",
        placeholder: "Enter each responsibility on a new line:\n• Leveraged cutting-edge AI and Cloud technologies\n• Utilized industry-standard tools and platforms\n• Spearheaded analysis of healthcare data",
        description: "List key responsibilities and achievements (one per line)",
        validation: z.string().min(10, "Please add at least one responsibility"),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        required: true,
        placeholder: "1",
        description: "Order in timeline (lower numbers appear first)",
        validation: z.number().min(0),
      },
    ],
    displayColumns: [
      { key: "position", label: "Position", sortable: true, width: "25%" },
      { key: "company", label: "Company", sortable: true, width: "25%" },
      { key: "duration", label: "Duration", sortable: true, width: "20%" },
      { key: "location", label: "Location", sortable: false, width: "15%" },
      { key: "displayOrder", label: "Order", sortable: true, width: "10%" },
    ],
    searchFields: ["position", "company", "location", "duration"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  "experience-content": {
    title: "Experience Section Content",
    description: "Manage experience section header, descriptions, and experience badge",
    apiEndpoint: "/api/admin/experience-content",
    fields: [
      {
        name: "sectionTag",
        label: "Section Tag",
        type: "text",
        required: true,
        placeholder: "Career Path",
        validation: z.string().min(1, "Section tag is required"),
      },
      {
        name: "sectionTitle",
        label: "Section Title",
        type: "text",
        required: true,
        placeholder: "Professional Experience",
        validation: z.string().min(1, "Section title is required"),
      },
      {
        name: "sectionDescription",
        label: "Section Description",
        type: "textarea",
        required: true,
        placeholder: "My professional journey in DevOps and software development, showcasing key roles and achievements.",
        validation: z.string().min(1, "Section description is required"),
      },
      {
        name: "experienceBadgeText",
        label: "Experience Badge Text",
        type: "text",
        required: true,
        placeholder: "2+ Years Experience",
        validation: z.string().min(1, "Experience badge text is required"),
      },
      {
        name: "projectsButtonText",
        label: "Projects Button Text",
        type: "text",
        required: true,
        placeholder: "See My Projects",
        validation: z.string().min(1, "Projects button text is required"),
      },
      {
        name: "projectsButtonUrl",
        label: "Projects Button URL",
        type: "text",
        required: true,
        placeholder: "#projects",
        validation: z.string().min(1, "Projects button URL is required"),
      },
      {
        name: "isActive",
        label: "Active Status",
        type: "select",
        required: true,
        options: [
          { value: "true", label: "✅ Active" },
          { value: "false", label: "❌ Inactive" },
        ],
        validation: z.boolean(),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "0",
        validation: z.number().min(0),
      },
    ],
    displayColumns: [
      { key: "sectionTag", label: "Tag", sortable: true, width: "15%" },
      { key: "sectionTitle", label: "Title", sortable: true, width: "20%" },
      { key: "sectionDescription", label: "Description", sortable: false, width: "25%" },
      { key: "experienceBadgeText", label: "Badge Text", sortable: false, width: "15%" },
      { key: "isActive", label: "Active", sortable: true, render: "boolean", width: "8%" },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date", width: "12%" },
      { key: "actions", label: "Actions", sortable: false, width: "5%" },
    ],
    searchFields: ["sectionTag", "sectionTitle", "sectionDescription", "experienceBadgeText"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  projects: {
    title: "Projects",
    description: "Showcase portfolio projects and technical work",
    apiEndpoint: "/api/admin/projects",
    fields: [
      {
        name: "title",
        label: "Project Title",
        type: "text",
        required: true,
        placeholder: "AI Mock Interview App",
      },
      {
        name: "description",
        label: "Project Description",
        type: "textarea",
        required: true,
        placeholder: "Developed an AI-driven job interview simulator with real-time feedback, integrating social/email authentication (via Clerk) and Google Gemini API for dynamic forms/questions. Deployed the application on Vercel for seamless performance.",
      },
      {
        name: "image",
        label: "Project Image Path",
        type: "text",
        required: true,
        placeholder: "/images/ai-interview-app.jpg",
      },
      {
        name: "technologies",
        label: "Technologies (JSON Format)",
        type: "textarea",
        required: true,
        placeholder: `[
  { "name": "Next.js", "bgColor": "bg-black dark:bg-gray-900", "textColor": "text-white dark:text-gray-100" },
  { "name": "React", "bgColor": "bg-blue-100 dark:bg-blue-900", "textColor": "text-blue-800 dark:text-blue-200" },
  { "name": "MongoDB", "bgColor": "bg-green-100 dark:bg-green-900", "textColor": "text-green-800 dark:text-green-200" }
]`,
      },
      {
        name: "demoUrl",
        label: "Demo/Live URL",
        type: "text",
        placeholder: "https://project-demo.com or #",
      },
      {
        name: "githubUrl",
        label: "GitHub Repository URL",
        type: "text",
        placeholder: "https://github.com/user/project or #",
      },
      {
        name: "featured",
        label: "Featured Project",
        type: "select",
        options: [
          { value: "true", label: "Yes" },
          { value: "false", label: "No" },
        ],
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "1",
      },
    ],
    displayColumns: [
      { key: "title", label: "Project Title", sortable: true },
      { key: "image", label: "Image", sortable: false },
      { key: "featured", label: "Featured", render: "boolean" },
      { key: "displayOrder", label: "Order", sortable: true },
    ],
    searchFields: ["title", "description", "technologies"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  certifications: {
    title: "Certifications & Awards",
    description: "Manage professional certifications, awards, courses and achievements",
    apiEndpoint: "/api/admin/certifications",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "Cloud Digital Leader Certification",
        validation: z.string().min(1, "Title is required"),
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Comprehensive description of the certification or award...",
        validation: z.string().min(10, "Description must be at least 10 characters"),
      },
      {
        name: "type",
        label: "Type",
        type: "select",
        required: true,
        options: [
          { value: "certificate", label: "🏆 Certificate" },
          { value: "award", label: "🥇 Award" },
          { value: "course", label: "📚 Course" },
          { value: "other", label: "📋 Other" },
        ],
        validation: z.enum(['certificate', 'award', 'course', 'other']),
      },
      {
        name: "issuer",
        label: "Issuing Organization",
        type: "text",
        required: true,
        placeholder: "Google Cloud",
        validation: z.string().min(1, "Issuer is required"),
      },
      {
        name: "date",
        label: "Date",
        type: "text",
        required: true,
        placeholder: "2023 or March 2022",
        validation: z.string().min(1, "Date is required"),
      },
      {
        name: "credentialId",
        label: "Credential ID",
        type: "text",
        placeholder: "ABC123DEF456",
      },
      {
        name: "url",
        label: "Verification URL",
        type: "text",
        placeholder: "https://verify.example.com/cert/123",
        validation: z.string().url("Please enter a valid URL").optional().or(z.literal("")),
      },
      {
        name: "expiryDate",
        label: "Expiry Date",
        type: "text",
        placeholder: "2025 or Never",
      },
      {
        name: "isActive",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { value: "true", label: "✅ Active" },
          { value: "false", label: "❌ Hidden" },
        ],
        validation: z.boolean(),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "0",
        validation: z.number().min(0, "Display order must be 0 or greater"),
      },
    ],
    displayColumns: [
      { key: "title", label: "Title", sortable: true, width: "25%" },
      { key: "type", label: "Type", sortable: true, render: "badge", width: "12%" },
      { key: "issuer", label: "Issuer", sortable: true, width: "20%" },
      { key: "date", label: "Date", sortable: true, width: "15%" },
      { key: "isActive", label: "Status", render: "boolean", width: "10%" },
      { key: "displayOrder", label: "Order", sortable: true, width: "8%" },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date", width: "10%" },
    ],
    searchFields: ["title", "description", "issuer", "type"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  blog: {
    title: "Blog Posts",
    description: "Create and manage blog content and articles",
    apiEndpoint: "/api/admin/blog",
    fields: [
      {
        name: "userId",
        label: "User ID",
        type: "text",
        required: true,
        placeholder: "auto-generated",
        description: "Author of the blog post",
        defaultValue: "675d7c65eb2a67f6f9e9d023",
        validation: z.string().min(1, "User ID is required"),
      },
      {
        name: "title",
        label: "Post Title",
        type: "text",
        required: true,
        placeholder: "Understanding React Hooks",
        validation: z.string().min(1, "Title is required"),
      },
      {
        name: "slug",
        label: "URL Slug",
        type: "text",
        required: true,
        placeholder: "understanding-react-hooks",
        description: "URL-friendly version of the title (lowercase, hyphens only)",
        validation: z.string().min(1, "Slug is required").regex(/^[a-z0-9-]+$/, "Slug must contain only lowercase letters, numbers, and hyphens"),
      },
      {
        name: "excerpt",
        label: "Excerpt",
        type: "textarea",
        required: true,
        placeholder: "Brief summary of the blog post for previews...",
        validation: z.string().min(10, "Excerpt must be at least 10 characters"),
      },
      {
        name: "content",
        label: "Content",
        type: "textarea",
        required: true,
        placeholder: "Full blog post content in Markdown format...",
        validation: z.string().min(50, "Content must be at least 50 characters"),
      },
      {
        name: "featuredImage",
        label: "Featured Image URL",
        type: "text",
        placeholder: "https://example.com/image.jpg",
        validation: z.string().url("Must be a valid URL").optional().or(z.literal("")),
      },
      {
        name: "category",
        label: "Category",
        type: "text",
        placeholder: "Technology, Tutorial, News",
      },
      {
        name: "tags",
        label: "Tags (comma-separated)",
        type: "text",
        placeholder: "react, javascript, frontend, tutorial",
        description: "Separate tags with commas",
      },
      {
        name: "status",
        label: "Publication Status",
        type: "select",
        required: true,
        options: [
          { value: "draft", label: "📝 Draft" },
          { value: "published", label: "✅ Published" },
          { value: "archived", label: "📁 Archived" },
        ],
        validation: z.enum(["draft", "published", "archived"]),
      },
      {
        name: "isPublished",
        label: "Published",
        type: "boolean",
        description: "Whether the post is published and visible to readers",
        validation: z.boolean().default(false),
      },
      {
        name: "isActive",
        label: "Active",
        type: "boolean",
        required: true,
        description: "Toggle to show/hide this post",
        validation: z.boolean().default(true),
      },
      {
        name: "isFeatured",
        label: "Featured Post",
        type: "boolean",
        description: "Featured posts appear prominently on the blog page",
        validation: z.boolean().default(false),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "0",
        description: "Lower numbers appear first",
        validation: z.number().default(0),
      },
      {
        name: "seoTitle",
        label: "SEO Title",
        type: "text",
        placeholder: "Optional custom title for search engines",
      },
      {
        name: "seoDescription",
        label: "SEO Description",
        type: "textarea",
        placeholder: "Custom description for search engines",
      },
      {
        name: "readTime",
        label: "Reading Time (minutes)",
        type: "number",
        placeholder: "5",
        description: "Estimated reading time in minutes",
      },
    ],
    displayColumns: [
      { key: "title", label: "Title", sortable: true, width: "25%" },
      { key: "status", label: "Status", sortable: true, render: "status", width: "10%" },
      { key: "category", label: "Category", sortable: true, width: "12%" },
      { key: "isActive", label: "Active", render: "boolean", sortable: true, width: "8%" },
      { key: "isPublished", label: "Published", render: "boolean", sortable: true, width: "8%" },
      { key: "isFeatured", label: "Featured", render: "boolean", sortable: true, width: "8%" },
      { key: "views", label: "Views", sortable: true, width: "8%" },
      { key: "createdAt", label: "Created", render: "date", sortable: true, width: "12%" },
      { key: "actions", label: "Actions", sortable: false, width: "9%" },
    ],
    searchFields: ["title", "excerpt", "category", "tags", "content"],
    defaultSort: { field: "createdAt", order: "desc" },
  },

  "blog-content": {
    title: "Blog Section Content",
    description: "Manage blog section header, descriptions, and display settings",
    apiEndpoint: "/api/admin/blog-content",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        placeholder: "Blog",
        validation: z.string().min(1, "Title is required"),
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "text",
        required: true,
        placeholder: "Insights, tutorials, and thoughts",
        validation: z.string().min(1, "Subtitle is required"),
      },
      {
        name: "description",
        label: "Section Description",
        type: "textarea",
        required: true,
        placeholder: "Welcome to my blog where I share insights about technology, development, and innovation.",
        validation: z.string().min(10, "Description must be at least 10 characters"),
      },
      {
        name: "seoTitle",
        label: "SEO Title",
        type: "text",
        placeholder: "Optional SEO title for the blog section",
      },
      {
        name: "seoDescription",
        label: "SEO Description",
        type: "textarea",
        placeholder: "SEO description for the blog section",
      },
      {
        name: "showRecentPosts",
        label: "Show Recent Posts",
        type: "boolean",
        description: "Display recent posts section",
        validation: z.boolean().default(true),
      },
      {
        name: "postsPerPage",
        label: "Posts Per Page",
        type: "number",
        required: true,
        placeholder: "6",
        description: "Number of posts to display per page",
        validation: z.number().min(1).max(50).default(6),
      },
      {
        name: "enableCategories",
        label: "Enable Categories",
        type: "boolean",
        description: "Show post categories",
        validation: z.boolean().default(true),
      },
      {
        name: "enableTags",
        label: "Enable Tags",
        type: "boolean",
        description: "Show post tags",
        validation: z.boolean().default(true),
      },
      {
        name: "enableSearch",
        label: "Enable Search",
        type: "boolean",
        description: "Show search functionality",
        validation: z.boolean().default(true),
      },
      {
        name: "enableComments",
        label: "Enable Comments",
        type: "boolean",
        description: "Allow comments on blog posts",
        validation: z.boolean().default(false),
      },
      {
        name: "isActive",
        label: "Blog Page Active",
        type: "boolean",
        required: true,
        description: "Enable/disable entire blog page and menu links",
        validation: z.boolean().default(true),
      },
    ],
    displayColumns: [
      { key: "title", label: "Title", sortable: true, width: "18%" },
      { key: "subtitle", label: "Subtitle", sortable: true, width: "22%" },
      { key: "isActive", label: "Active", render: "boolean", sortable: true, width: "10%" },
      { key: "postsPerPage", label: "Posts/Page", sortable: true, width: "10%" },
      { key: "showRecentPosts", label: "Recent Posts", render: "boolean", width: "10%" },
      { key: "enableCategories", label: "Categories", render: "boolean", width: "10%" },
      { key: "enableTags", label: "Tags", render: "boolean", width: "8%" },
      { key: "updatedAt", label: "Updated", render: "date", sortable: true, width: "12%" },
    ],
    searchFields: ["title", "subtitle", "description"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  testimonials: {
    title: "Testimonials",
    description: "Manage client testimonials and recommendations",
    apiEndpoint: "/api/admin/testimonials",
    fields: [
      {
        name: "name",
        label: "Client Name",
        type: "text",
        required: true,
        placeholder: "John Smith",
      },
      {
        name: "position",
        label: "Position",
        type: "text",
        placeholder: "CEO at TechCorp",
      },
      {
        name: "company",
        label: "Company",
        type: "text",
        placeholder: "TechCorp Inc.",
      },
      {
        name: "testimonial",
        label: "Testimonial",
        type: "textarea",
        required: true,
        placeholder: "Outstanding work and professionalism...",
      },
      {
        name: "rating",
        label: "Rating",
        type: "select",
        options: [
          { value: "5", label: "⭐⭐⭐⭐⭐ (5)" },
          { value: "4", label: "⭐⭐⭐⭐ (4)" },
          { value: "3", label: "⭐⭐⭐ (3)" },
          { value: "2", label: "⭐⭐ (2)" },
          { value: "1", label: "⭐ (1)" },
        ],
      },
      {
        name: "avatar",
        label: "Avatar URL",
        type: "text",
        placeholder: "/images/avatar.jpg",
      },
    ],
    displayColumns: [
      { key: "name", label: "Name", sortable: true },
      { key: "company", label: "Company", sortable: true },
      { key: "rating", label: "Rating", sortable: true },
      { key: "createdAt", label: "Added", sortable: true, render: "date" },
    ],
    searchFields: ["name", "company", "testimonial"],
    defaultSort: { field: "createdAt", order: "desc" },
  },

  services: {
    title: "Services",
    description: "Manage services offered and pricing information",
    apiEndpoint: "/api/admin/services",
    fields: [
      {
        name: "title",
        label: "Service Title",
        type: "text",
        required: true,
        placeholder: "Web Development",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Complete web development services...",
      },
      {
        name: "features",
        label: "Features",
        type: "textarea",
        placeholder: "List key features, one per line",
      },
      {
        name: "price",
        label: "Starting Price",
        type: "text",
        placeholder: "$999",
      },
      {
        name: "duration",
        label: "Typical Duration",
        type: "text",
        placeholder: "2-4 weeks",
      },
      {
        name: "icon",
        label: "Icon",
        type: "text",
        placeholder: "code, design, database",
      },
    ],
    displayColumns: [
      { key: "title", label: "Service", sortable: true },
      { key: "price", label: "Price", sortable: true },
      { key: "duration", label: "Duration", sortable: false },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date" },
    ],
    searchFields: ["title", "description"],
    defaultSort: { field: "title", order: "asc" },
  },

  "social-links": {
    title: "Social Links",
    description: "Manage social media profiles and contact links",
    apiEndpoint: "/api/admin/social-links",
    fields: [
      {
        name: "platform",
        label: "Platform",
        type: "text",
        required: true,
        placeholder: "GitHub, LinkedIn, Twitter",
      },
      {
        name: "url",
        label: "Profile URL",
        type: "text",
        required: true,
        placeholder: "https://github.com/username",
      },
      {
        name: "icon",
        label: "Icon",
        type: "text",
        placeholder: "github, linkedin, twitter",
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "1",
      },
    ],
    displayColumns: [
      { key: "platform", label: "Platform", sortable: true },
      { key: "url", label: "URL", sortable: false },
      { key: "displayOrder", label: "Order", sortable: true },
    ],
    searchFields: ["platform"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  footer: {
    title: "Footer Content",
    description: "Manage footer sections, contact info and social links",
    apiEndpoint: "/api/admin/footer",
    fields: [
      {
        name: "getInTouchTitle",
        label: "Get in Touch Title",
        type: "text",
        required: true,
        placeholder: "Get in Touch",
      },
      {
        name: "followMeTitle",
        label: "Follow Me Title",
        type: "text",
        required: true,
        placeholder: "Follow Me",
      },
      {
        name: "quickLinksTitle",
        label: "Quick Links Title",
        type: "text",
        required: true,
        placeholder: "Quick Links",
      },
      {
        name: "copyrightText",
        label: "Copyright Text",
        type: "text",
        required: true,
        placeholder: "© 2024 Your Name. All rights reserved.",
      },
    ],
    displayColumns: [
      { key: "getInTouchTitle", label: "Contact Title", sortable: false },
      { key: "followMeTitle", label: "Social Title", sortable: false },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date" },
    ],
    searchFields: ["getInTouchTitle", "followMeTitle", "copyrightText"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  settings: {
    title: "Site Settings",
    description: "Global site configuration and preferences",
    apiEndpoint: "/api/admin/settings",
    fields: [
      {
        name: "siteName",
        label: "Site Name",
        type: "text",
        required: true,
        placeholder: "My Portfolio",
      },
      {
        name: "siteDescription",
        label: "Site Description",
        type: "textarea",
        required: true,
        placeholder: "Professional portfolio showcasing my work...",
      },
      {
        name: "contactEmail",
        label: "Contact Email",
        type: "email",
        required: true,
        placeholder: "contact@example.com",
      },
      {
        name: "phoneNumber",
        label: "Phone Number",
        type: "text",
        placeholder: "+1 (555) 123-4567",
      },
      {
        name: "address",
        label: "Address",
        type: "textarea",
        placeholder: "123 Main St, City, State 12345",
      },
      {
        name: "timezone",
        label: "Timezone",
        type: "text",
        placeholder: "America/New_York",
      },
    ],
    displayColumns: [
      { key: "siteName", label: "Site Name", sortable: true },
      { key: "contactEmail", label: "Contact Email", sortable: true },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date" },
    ],
    searchFields: ["siteName", "siteDescription", "contactEmail"],
    defaultSort: { field: "updatedAt", order: "desc" },
  },

  "contact-content": {
    title: "Contact Section Content",
    description: "Manage contact section headers, information, and form labels",
    apiEndpoint: "/api/admin/contact-content",
    fields: [
      {
        name: "sectionType",
        label: "Section Type",
        type: "select",
        required: true,
        options: [
          { value: "header", label: "📋 Section Header" },
          { value: "contact-info", label: "📞 Contact Information" },
          { value: "form-labels", label: "📝 Form Labels" },
        ],
        validation: z.enum(["header", "contact-info", "form-labels"]),
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "e.g., Get In Touch, Contact Information",
        validation: z.string().min(1, "Title is required"),
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        placeholder: "e.g., Let's Talk",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        placeholder: "e.g., Feel free to reach out for collaborations...",
      },
      {
        name: "email",
        label: "Contact Email",
        type: "email",
        placeholder: "devops.portfolio@example.com",
        validation: z.string().email().optional().or(z.literal("")),
      },
      {
        name: "phone",
        label: "Phone Number",
        type: "text",
        placeholder: "+1 555-123-4567",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        placeholder: "San Francisco, CA, USA",
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        placeholder: "0",
        validation: z.number().min(0),
      },
      {
        name: "isActive",
        label: "Active Status",
        type: "select",
        required: true,
        options: [
          { value: "true", label: "✅ Active" },
          { value: "false", label: "❌ Inactive" },
        ],
        validation: z.boolean(),
      },
    ],
    displayColumns: [
      { key: "sectionType", label: "Type", sortable: true },
      { key: "title", label: "Title", sortable: true },
      { key: "subtitle", label: "Subtitle", sortable: false },
      { key: "isActive", label: "Active", sortable: true, render: "boolean" },
      { key: "displayOrder", label: "Order", sortable: true },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date" },
    ],
    searchFields: ["title", "subtitle", "description", "email", "phone", "location"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  "skill-categories": {
    title: "Skill Categories",
    description: "Manage skill categories (Programming Languages, Frameworks, etc.)",
    apiEndpoint: "/api/admin/skill-categories",
    fields: [
      {
        name: "name",
        label: "Category Name",
        type: "text",
        required: true,
        placeholder: "Programming Languages",
        validation: z.string().min(1, "Category name is required"),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        required: true,
        placeholder: "1",
        description: "Order in which categories appear (lower numbers first)",
        validation: z.number().min(0),
      },
      {
        name: "isActive",
        label: "Active Status",
        type: "switch",
        required: false,
        description: "Toggle to show or hide this category on the website",
        validation: z.boolean().default(true),
      },
    ],
    displayColumns: [
      { key: "name", label: "Category Name", sortable: true, width: "40%" },
      { key: "displayOrder", label: "Display Order", sortable: true, width: "20%" },
      { key: "isActive", label: "Status", render: "boolean", width: "15%" },
      { key: "updatedAt", label: "Updated", sortable: true, render: "date", width: "20%" },
      { key: "actions", label: "Actions", sortable: false, width: "5%" },
    ],
    searchFields: ["name"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },

  skills: {
    title: "Skills",
    description: "Manage individual skills and their proficiency levels",
    apiEndpoint: "/api/admin/skills",
    fields: [
      {
        name: "categoryId",
        label: "Category",
        type: "select",
        required: true,
        apiOptions: "/api/admin/skill-categories",
        optionValue: "_id",
        optionLabel: "name",
        placeholder: "Select a category",
        validation: z.string().min(1, "Category is required"),
      },
      {
        name: "name",
        label: "Skill Name",
        type: "text",
        required: true,
        placeholder: "Python",
        validation: z.string().min(1, "Skill name is required"),
      },
      {
        name: "icon",
        label: "Icon URL",
        type: "text",
        placeholder: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
        description: "URL to the skill icon (devicons recommended)",
        validation: z.string().url("Must be a valid URL").optional().or(z.literal("")),
      },
      {
        name: "proficiency",
        label: "Proficiency Level (%)",
        type: "number",
        required: true,
        placeholder: "85",
        description: "Proficiency level from 0 to 100",
        validation: z.number().min(0).max(100),
      },
      {
        name: "years",
        label: "Years of Experience",
        type: "text",
        placeholder: "2+ years",
        description: "Optional years of experience text",
        validation: z.string().optional(),
      },
      {
        name: "displayOrder",
        label: "Display Order",
        type: "number",
        required: true,
        placeholder: "1",
        description: "Order within the category (lower numbers first)",
        validation: z.number().min(0),
      },
      {
        name: "isActive",
        label: "Active Status",
        type: "switch",
        required: false,
        description: "Toggle to show or hide this skill on the website",
        validation: z.boolean().default(true),
      },
    ],
    displayColumns: [
      { key: "name", label: "Skill Name", sortable: true, width: "25%" },
      { key: "categoryId", label: "Category", sortable: true, width: "20%" },
      { key: "proficiency", label: "Proficiency", sortable: true, width: "15%" },
      { key: "years", label: "Experience", sortable: false, width: "15%" },
      { key: "displayOrder", label: "Order", sortable: true, width: "10%" },
      { key: "isActive", label: "Status", render: "boolean", width: "10%" },
      { key: "actions", label: "Actions", sortable: false, width: "5%" },
    ],
    searchFields: ["name", "years"],
    defaultSort: { field: "displayOrder", order: "asc" },
  },
};

export function getAdminConfig(tab: string): AdminTabConfig | null {
  return adminConfigs[tab] || null;
}

export function getAdminTabs(): Array<{ id: string; label: string; description: string }> {
  return Object.entries(adminConfigs).map(([id, config]) => ({
    id,
    label: config.title,
    description: config.description,
  }));
}